# Generated by Django 5.0.3 on 2024-03-12 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingitem',
            old_name='quantity',
            new_name='days',
        ),
    ]
